# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'MXDouYuZhiBo' do
pod 'Alamofire', '~> 4.0.1'
pod 'Kingfisher', '~> 3.1.4'

end

target 'MXDouYuZhiBoTests' do

end

target 'MXDouYuZhiBoUITests' do

end

